# Generated by Django 2.2.16 on 2020-09-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='uname',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
    ]
