# Generated by Django 2.2.16 on 2020-09-07 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200907_1512'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinfo',
            table='user',
        ),
    ]
