# Generated by Django 2.2.16 on 2020-09-04 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0004_areainfo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='areainfo',
            table='area',
        ),
    ]
